name: CICD - MAIN

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  Build:
    uses: devops-shop/roboshop-github-actions/.github/workflows/cicd-main.yml@main
    with:
      appType: 'nodejs'
      appName: 'cart'
    secrets:
      vault_token: ${{ secrets.vault_token }}
